import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./NavBar";
import { Theme } from "@radix-ui/themes";

// Creating an instance of the Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

/**
 * Metadata for the RootLayout component.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component to wrap the main content with common styles and structure.
 * @param {React.ReactNode} children - The content to be wrapped.
 * @returns {JSX.Element} The wrapped content.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="autumn">
      <body className={inter.className}>
        {/* Apply Radix UI theme */}
        <Theme>
          {/* Render the navigation bar */}
          <NavBar />
          {/* Render the main content */}
          <main>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
